# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Auth
      run: dotnet build --no-restore --configuration Release Throneteki.Auth
    - name: Publish Auth
      run: dotnet dotnet publish Throneteki.Auth -c Release -o ${{env.DOTNET_ROOT}}/Throneteki.Auth
    - name: Build Lobby
      run: dotnet build --no-restore --configuration Release Throneteki.Lobby
    - name: Publish Lobby
      run: dotnet dotnet publish Throneteki.Lobby -c Release -o ${{env.DOTNET_ROOT}}/Throneteki.Lobby
